### PR TITLE
Fix input label position

### LINKED ISSUE #104: Fix input label display issue
For the inputs with a placeholder the label stays on top of the placeholder.

image

### PR DESCRIPTION
**Pull request by herzzanu**
Fixes #104

### CODE REVIEW

File: addon/components/bsy-input-addon/input.js [hunk 1]
```diff
@@ -4,11 +4,12 @@ import layout from '../../templates/components/bsy-input-addon/input';
 const BsyInputAddonInputComponent = Component.extend({
   layout,
   tagName: "div",
+  classNameBindings: ["value:filled", "placeholder:filled"],
```
Comment (Exelord) [inline addon/components/bsy-input-addon/input.js]: this still doesn't work for input's type="data" :/

Comment (Exelord) [reply addon/components/bsy-input-addon/input.js]: as the placeholder is not control by html dom

Comment (herzzanu) [reply addon/components/bsy-input-addon/input.js]: Works for me. The only thing that's not working is when you focus the field and then unfocus it. That's when `filled` class is lost.
