### PR TITLE
Fix bsy dialog style

### LINKED ISSUE #102: Fix bsy-dialog style
We have override sweetalert styles to fit our apps style but sweetalert changed classes in never versions so our overrides doesn't work now. We should try to style it on our own to not depend on their classes.

### PR DESCRIPTION
**Pull request by JovicaSusa**
This should fix #102

### CODE REVIEW

File: blueprints/ember-cli-bootstrap-bookingsync-sass/index.js [hunk 1]
```diff
@@ -16,6 +16,6 @@ module.exports = {
   },
 
   afterInstall() {
-    return this.addPackageToProject('sweetalert2');
+    return this.addPackageToProject('sweetalert2@7.3.5');
```
Comment (herzzanu) [inline blueprints/ember-cli-bootstrap-bookingsync-sass/index.js]: I think this is not necessary since it will pick the specified version in the `package.json`. I see you've already locked in the version there.

Comment (JovicaSusa) [reply blueprints/ember-cli-bootstrap-bookingsync-sass/index.js]: I've tried it locally and without version declared here it will import latest version.

Comment (herzzanu) [reply blueprints/ember-cli-bootstrap-bookingsync-sass/index.js]: When you tried it locally did you use your local branch of the addon or the remote one?

Comment (JovicaSusa) [reply blueprints/ember-cli-bootstrap-bookingsync-sass/index.js]: remote one.
